fix(CI): checks before image and ci failure checks

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,8 +11,78 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  Sanity_Checks:
+    name: Sanity Checks
+    runs-on: ubuntu-latest
+    container:
+      image: ${{ vars.DEVTOOLS_IMAGE || 'ghcr.io/landsandboat/devtools:ubuntu' }}
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Run checks
+        run: ./tools/ci/sanity_checks.sh
+
+      - name: Add sanity checks report to summary
+        if: ${{ always() }}
+        run: tr -d '\r' < sanity_checks_summary.md >> $GITHUB_STEP_SUMMARY
+
+  Lua_Language_Server:
+    name: Lua Language Server
+    runs-on: ubuntu-latest
+    container:
+      image: ${{ vars.DEVTOOLS_IMAGE || 'ghcr.io/landsandboat/devtools:ubuntu' }}
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Run Lua Language Server
+        id: run_lls
+        run: python ./tools/ci/lua_lang_server.py
+
+      - name: Summarize run
+        id: summarize_run
+        run: |
+          found_issues=false
+          check_file=lua_lang_errors.txt
+          if [[ -f "$check_file" && -s "$check_file" ]]; then
+              found_issues=true
+              echo "## :x: Run Failed" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+              tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+              echo "" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "$found_issues" == "false" ]]; then
+              if [[ "${{ steps.run_lls.outcome }}" == "success" ]]; then
+                  echo "## :heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
+              else
+                  echo "## :x: Lua Language Server had errors, but no specific output was found." >> $GITHUB_STEP_SUMMARY
+                  echo "Check the logs step for details." >> $GITHUB_STEP_SUMMARY
+                  found_issues=true
+              fi
+          fi
+          echo "issues_found=$found_issues" >> $GITHUB_OUTPUT
+
+      - name: Fail Workflow if Checks Failed
+        if: ${{ steps.run_lls.outcome == 'failure' || steps.summarize_run.outputs.issues_found == 'true' }}
+        run: |
+          echo "Lua Language Server failed. See summary for details."
+          exit 1
+
   Docker_Build:
     name: ${{ matrix.save_cache && 'Cache Build' || 'Build' }}
+    needs: [Sanity_Checks, Lua_Language_Server]
     strategy:
       fail-fast: false
       matrix:
